#ifndef BOOSTER_TEXT_TEMPLATE_NODE_HPP_INCLUDED
#define BOOSTER_TEXT_TEMPLATE_NODE_HPP_INCLUDED

#include <booster/text_template/common.hpp>
#include <booster/text_template/input_position.hpp>

namespace booster {
    namespace text_template {
        
        // =====================================================================
        // Interface
        // =====================================================================
        
        /*!
         \brief The node class represents a parse tree element generated by one
         or more input characters.
         
         This is an abstract base class, as the derived classes are used for
         specific purposes (e.g., unparsed text, the print instruction, etc).
         */
        class node {
        public:
            
            // -----------------------------------------------------------------
            // Lifecycle
            // -----------------------------------------------------------------
            
            node() : position_() {}
            
            node(const input_position& p)
            : position_(p) {}
            
            virtual ~node() = 0;
            
            // -----------------------------------------------------------------
            // Execution
            // -----------------------------------------------------------------
            
            virtual void execute(std::ostream& os) = 0;
            
            // -----------------------------------------------------------------
            // Variables
            // -----------------------------------------------------------------
            
        private:
            
            input_position position_;
            
        };

        // =====================================================================
        // Implementation
        // =====================================================================
        
        inline node::~node() {}
        
    }
}

#endif // #ifndef BOOSTER_TEXT_TEMPLATE_NODE_HPP_INCLUDED
